MinimercadoAlfredo/Models/Provider.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MinimercadoAlfredo.Models
{
    public class Provider
    {
        [Key]
        public int IdProvider { get; set; }

        [Display(Name = "Proveedor")]
        [Required(ErrorMessage = "Campo Obligatorio")]
        public string ProviderName { get; set; }

        [Display(Name = "Dirección")]
        public string ProviderAddress { get; set; }

        [Display(Name = "Teléfono")]
        public int? ProviderPhone { get; set; }

        public string ProviderEmail { get; set; }

        public virtual ICollection<ProductProvider> Products { get; set; }
    }
}

MinimercadoAlfredo/Controllers/ProvidersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MinimercadoAlfredo.Context;
using MinimercadoAlfredo.Models;

namespace MinimercadoAlfredo.Controllers
{
    public class ProvidersController : Controller
    {
        private AlfredoContext db = new AlfredoContext();

        // GET: Providers
        public ActionResult Index()
        {
            return View(db.Providers.ToList());
        }

        // GET: Providers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Provider provider = db.Providers.Find(id);
            if (provider == null)
            {
                return HttpNotFound();
            }
            return View(provider);
        }

        // GET: Providers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Providers/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdProvider,ProviderName,ProviderAddress,ProviderPhone,ProviderEmail")] Provider provider)
        {
            if (ModelState.IsValid)
            {
                db.Providers.Add(provider);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(provider);
        }

        // GET: Providers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Provider provider = db.Providers.Find(id);
            if (provider == null)
            {
                return HttpNotFound();
            }
            return View(provider);
        }

        // POST: Providers/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdProvider,ProviderName,ProviderAddress,ProviderPhone,ProviderEmail")] Provider provider)
        {
            if (ModelState.IsValid)
            {
                db.Entry(provider).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(provider);
        }

        // GET: Providers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Provider provider = db.Providers.Find(id);
            if (provider == null)
            {
                return HttpNotFound();
            }
            return View(provider);
        }

        // POST: Providers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Provider provider = db.Providers.Find(id);
            db.Providers.Remove(provider);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MinimercadoAlfredo/Views/Providers/Create.cshtml
@model MinimercadoAlfredo.Models.Provider

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Provider</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProviderName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProviderAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProviderPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProviderEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MinimercadoAlfredo/Views/Providers/Delete.cshtml
@model MinimercadoAlfredo.Models.Provider

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Provider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProviderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProviderAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProviderPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProviderEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderEmail)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MinimercadoAlfredo/Views/Providers/Details.cshtml
@model MinimercadoAlfredo.Models.Provider

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Provider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProviderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProviderAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProviderPhone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderPhone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProviderEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProviderEmail)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdProvider }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MinimercadoAlfredo/Views/Providers/Edit.cshtml
@model MinimercadoAlfredo.Models.Provider

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Provider</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdProvider)

        <div class="form-group">
            @Html.LabelFor(model => model.ProviderName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProviderAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProviderPhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderPhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderPhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProviderEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProviderEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProviderEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MinimercadoAlfredo/Views/Providers/Index.cshtml
@model IEnumerable<MinimercadoAlfredo.Models.Provider>

@{
    ViewBag.Title = "Index";
}

<h2 class="text-center">Lista de Proveedores</h2>
<hr style="color:grey;border-color:grey" />

<div>
    <a href="@Url.Action("Create", "Providers")" class="btn btn-success">Agregar Proveedor</a>
</div>
<br />
<table class="table table-striped table-bordered" id="tabla">
    <thead>
        <tr class="text-center" style="color:white; background-color:#4d77a3">
            <th>
                @Html.DisplayNameFor(model => model.ProviderName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProviderAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProviderPhone)
            </th>
            <th>
                Email
            </th>
            <th class="text-center">Acciones</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProviderName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProviderAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProviderPhone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProviderEmail)
                </td>
                <td class="text-center">
                    @Html.ActionLink("Editar", "Edit", new { id = item.IdProvider }, new { @class = "btn btn-primary btn-sm" })
                    @Html.ActionLink("Detalles", "Details", new { id = item.IdProvider }, new { @class = "btn btn-primary btn-sm" })
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.IdProvider }, new { @class = "btn btn-primary btn-sm" })
                </td>
            </tr>
        }
    </tbody>

</table>

@section scripts
{
    <script>
        $(document).ready(function () {

            ////Grilla automatica//
            $("#tabla").DataTable({
                "language": { "url": "/Scripts/DataTables/spanish.json" }
            });

        })
    </script>
}