MinimercadoAlfredo/Controllers/PurchasesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MinimercadoAlfredo.Context;
using MinimercadoAlfredo.Models;
using MinimercadoAlfredo.ViewModels;

namespace MinimercadoAlfredo.Controllers
{
    public class PurchasesController : Controller
    {
        private AlfredoContext db = new AlfredoContext();

        // GET: Purchases
        public ActionResult Index()
        {
            var purchases = db.Purchases.Include(p => p.Provider);
            return View(purchases.ToList().OrderByDescending(p => p.PurchaseDate));
        }

        // GET: Purchases/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Purchase purchase = db.Purchases.Find(id);
            if (purchase == null)
            {
                return HttpNotFound();
            }
            return View(purchase);
        }

        // GET: Purchases/Create
        public ActionResult Create()
        {
            ViewBag.Providers = db.Providers.ToList().OrderBy(p => p.ProviderName);
            ViewBag.Products = db.Products.ToList().OrderBy(p => p.ProductDescription);
            return View("CreatePurchase");
        }

        // POST: Purchases/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public JsonResult Create(PurchaseVM purchase)
        {
            bool status = false;
            Purchase p = new Purchase();
            var idprovider = Int32.Parse(purchase.ProviderName);

            if (ModelState.IsValid)
            {
                p.IdProvider = idprovider;
                p.PurchaseDate = purchase.PurchaseDate;
                p.Comments = purchase.PurchaseComments;
                p.PurchaseTotal = purchase.PurchaseTotal;

                db.Purchases.Add(p);
                db.SaveChanges();

                foreach (var item in purchase.PurchaseLines)
                {
                    PurchaseLine purchaseline = new PurchaseLine();
                    purchaseline.IdPurchase = p.IdPurchase;
                    purchaseline.IdProduct = item.IdProduct;
                    purchaseline.Cost = item.Cost;
                    purchaseline.PurchaseQuantity = item.PurchaseQuantity;
                    purchaseline.LineTotal = item.LineTotal;

                    db.PurchaseLines.Add(purchaseline);
                    db.SaveChanges();
                }
                status = true;
            }

            return new JsonResult { Data = new { status = status } };
        }

        // GET: Purchases/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Purchase purchase = db.Purchases.Find(id);
            if (purchase == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdProvider = new SelectList(db.Providers, "IdProvider", "ProviderName", purchase.IdProvider);
            return View(purchase);
        }

        // POST: Purchases/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPurchase,PurchaseDate,Comments,PurchaseTotal,IdProvider")] Purchase purchase)
        {
            if (ModelState.IsValid)
            {
                db.Entry(purchase).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdProvider = new SelectList(db.Providers, "IdProvider", "ProviderName", purchase.IdProvider);
            return View(purchase);
        }

        // GET: Purchases/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Purchase purchase = db.Purchases.Find(id);
            if (purchase == null)
            {
                return HttpNotFound();
            }
            return View(purchase);
        }

        // POST: Purchases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Purchase purchase = db.Purchases.Find(id);
            db.Purchases.Remove(purchase);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MinimercadoAlfredo/Views/Purchases/Create.cshtml
@model MinimercadoAlfredo.Models.Purchase

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Purchase</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PurchaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PurchaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchaseTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PurchaseTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchaseTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdProvider, "IdProvider", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idProvider", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdProvider, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MinimercadoAlfredo/Views/Purchases/Delete.cshtml
@model MinimercadoAlfredo.Models.Purchase

@{
    Layout = null;
}

<h2 class="text-center">Eliminar Producto</h2>

<h3>¿Está seguro de eliminar el siguiente Producto?</h3>
<div>
    <h4>Purchase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Provider.ProviderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Provider.ProviderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseTotal)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MinimercadoAlfredo/Views/Purchases/Details.cshtml
@model MinimercadoAlfredo.Models.Purchase

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Purchase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Provider.ProviderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Provider.ProviderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PurchaseTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PurchaseTotal)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdPurchase }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MinimercadoAlfredo/Views/Purchases/Edit.cshtml
@model MinimercadoAlfredo.Models.Purchase

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Purchase</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdPurchase)

        <div class="form-group">
            @Html.LabelFor(model => model.PurchaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PurchaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchaseTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PurchaseTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchaseTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdProvider, "IdProvider", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdProvider", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdProvider, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MinimercadoAlfredo/Views/Purchases/Index.cshtml
@model IEnumerable<MinimercadoAlfredo.Models.Purchase>

@{
    ViewBag.Title = "Index";
}

<h2 class="text-center">Lista de Compras</h2>
<hr style="color:grey;border-color:grey" />

<div>
    <a href="@Url.Action("Create", "Purchases")" class="btn btn-success">Nueva Compra</a>
</div>
<br />
<table class="table table-striped table-bordered" id="tabla">
    <thead>
        <tr class="text-center" style="color:white; background-color:#4d77a3">
            <th>
                Fecha de Compra
            </th>
            <th>
                Proveedor
            </th>          
            <th>
                Total Comprado
            </th>
            <th class="text-center">
                Acciones
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PurchaseDate)
                </td>
                <td width="250px">
                    @Html.DisplayFor(modelItem => item.Provider.ProviderName)
                </td>                
                <td>
                    @Html.DisplayFor(modelItem => item.PurchaseTotal)
                </td>
                <td class="text-center">
                    @Html.ActionLink("Editar", "Edit", new { id = item.IdPurchase }, new {@class = "btn btn-primary btn-sm" }) 
                    @Html.ActionLink("Detalles", "Details", new { id = item.IdPurchase }, new { @class = "btn btn-primary btn-sm" }) 
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.IdPurchase }, new { @class = "btn btn-primary btn-sm" })
                </td>
            </tr>
        }
    </tbody>

</table>

@section scripts
{
    <script>
        $(document).ready(function () {

            //Grilla automatica//
            $("#tabla").DataTable({order: [[0, "desc"]],
                "language": { "url": "/Scripts/DataTables/spanish.json" }
            });           
            
        })
    </script>    
}